name: Deploy complex Docker app
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t korzunyury/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true korzunyury/react-test npm test

      - run: docker build -t korzunyury/complex-client ./client
      - run: docker build -t korzunyury/complex-nginx ./nginx
      - run: docker build -t korzunyury/complex-server ./server
      - run: docker build -t korzunyury/complex-worker ./worker

      - run: docker push korzunyury/complex-client
      - run: docker push korzunyury/complex-nginx
      - run: docker push korzunyury/complex-server
      - run: docker push korzunyury/complex-worker

